#ifndef DEVICEHUB_CPP_GLOBAL_H
#define DEVICEHUB_CPP_GLOBAL_H

#if defined(DEVICEHUB_CPP_LIBRARY)
#  define DEVICEHUB_CPPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DEVICEHUB_CPPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEVICEHUB_CPP_GLOBAL_H
